dist: trusty
sudo: required
language: java
jdk: oraclejdk11
      
services:
- xvfb

addons:
  chrome: stable

before_install:
  - wget https://chromedriver.storage.googleapis.com/2.38/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - sudo cp chromedriver /usr/bin
  
script: 
- mvn clean install
